### ISSUE TITLE
it's not compatible with requirejs

### ISSUE THREAD

**Issue by yavuz** [alexcodito/KnockoutContextHover#6]
Hi
If you use requirejs, unfortunately it doesn't work. Because "ko" can not find.

> ReferenceError: ko is not defined

for example requirejs in magento 2.

**Comment by di-repo** [comment]
Hi, thanks for the awesome addon, it works much better for me than the chrome knockout plugin.
As @yavuz has already mentioned it doesn't seem to work with Magento. I see that the issue is Knockout is not exposed in a global context. 
A simple fix would be - Before starting Knockout Context Hover open the console and run:
`require(
  ['ko'],
	function (ko) {
    window.ko = ko;
  }
);`
After that, you can trigger the Knockout Context Hover and it will run just fine.
I am not very good at Firefox add-on development, so I don't feel confident enough to do a PR
but a simple check if ko is not present and page is using requirejs try to load it with require (actually I think you don't even need to load it just check if it's available).
You can also put this "init" script in the Head section on your local dev instance. So far seems to work for me, but a real fix will be much welcomed.
I am not sure that it works on 100% but at least you can check some things.
